import type React from 'react';

export type ReiconName =
  | 'calendar'
  | 'calendar-check'
  | 'calendar-days'
  | 'check'
  | 'circle-check'
  | 'circle-alert'
  | 'circle-plus'
  | 'circle-user-round'
  | 'x'
  | 'alert-circle'
  | 'alert-triangle'
  | 'triangle-alert'
  | 'octagon-x'
  | 'info'
  | 'search'
  | 'search-x'
  | 'paperclip'
  | 'file'
  | 'file-text'
  | 'image'
  | 'download'
  | 'eye'
  | 'eye-off'
  | 'bell'
  | 'bell-ring'
  | 'settings'
  | 'refresh'
  | 'refresh-cw'
  | 'upload'
  | 'upload-cloud'
  | 'cloud'
  | 'logout'
  | 'lock'
  | 'key'
  | 'key-round'
  | 'shield-check'
  | 'graduation-cap'
  | 'message-square'
  | 'message-circle'
  | 'chat-line'
  | 'megaphone'
  | 'heart-handshake'
  | 'sparkles'
  | 'party-popper'
  | 'wifi-off'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevrons-left'
  | 'chevrons-right'
  | 'user-x'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-up-right'
  | 'plus'
  | 'pencil'
  | 'trash'
  | 'trash-2'
  | 'user'
  | 'users'
  | 'user-round'
  | 'user-check'
  | 'user-cog'
  | 'loader'
  | 'clock'
  | 'folder'
  | 'folder-open'
  | 'inbox'
  | 'external-link'
  | 'filter'
  | 'zoom-in'
  | 'zoom-out'
  | 'sun'
  | 'moon'
  | 'flag'
  | 'layers'
  | 'clipboard-list'
  | 'scroll-text'
  | 'credit-card'
  | 'volume-x'
  | 'activity'
  | 'notebook-pen'
  | 'github'
  | 'globe'
  | 'linkedin'
  | 'smartphone'
  | 'monitor'
  | 'cctv'
  | 'more-horizontal'
  | 'more-vertical'
  | 'ellipsis-vertical'
  | 'grip-vertical'
  | 'columns-3'
  | 'panel-left'
  | 'sidebar-left'
  | 'trending-up'
  | 'mail'
  | 'send'
  | 'plane'
  | 'share'
  | 'box'
  | 'code';

export type ReillustrationName =
  | 'empty-today'
  | 'empty-assignments'
  | 'empty-attachments'
  | 'empty-search'
  | 'empty-completed'
  | 'empty-notices'
  | 'celebration-holiday'
  | 'offline-disconnected'
  | 'error-warning'
  | 'auth-shield'
  | 'exam-prep'
  | 'messages-empty-student'
  | 'messages-empty-teacher'
  | 'messages-empty-admin'
  | 'teacher-overview-empty'
  | 'admin-overview-empty'
  | 'student-requests-empty'
  | 'classwork-empty'
  | 'empty-leave'
  | 'empty-notifications'
  | 'welcome-student'
  | 'welcome-teacher'
  | 'welcome-admin'
  | 'streak-celebration'
  | 'filter-no-results'
  | 'security-lockout'
  | 'study-desk'
  | 'exam-countdown'
  | 'announcements-bulletin'
  | 'maintenance-tuning';

export type ReiconPreset =
  | 'bounce'
  | 'rotate'
  | 'gear'
  | 'ring'
  | 'spin'
  | 'pulse'
  | 'scale'
  | 'shake'
  | 'lift'
  | 'zoom'
  | 'none';

export interface ReiconProps extends React.SVGAttributes<SVGSVGElement> {
  name: ReiconName;
  size?: number | string;
  className?: string;
  preset?: ReiconPreset;
  isLoading?: boolean;
  isActive?: boolean;
  isFilled?: boolean;
  color?: string;
  strokeWidth?: number | string;
  weight?: string;
}

export type ReillustrationSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;

export interface ReillustrationProps extends React.SVGAttributes<SVGSVGElement> {
  name: ReillustrationName;
  size?: ReillustrationSize;
  className?: string;
  interactive?: boolean;
}
